CREATE TABLE goods (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  vendor_code VARCHAR(20) NOT NULL COMMENT '공급사 벤더코드 (V-ADMN: 관리자 직영)',
  vendor_goods_code VARCHAR(100) DEFAULT NULL COMMENT '업체 자체 상품 코드',
  category_id INT UNSIGNED DEFAULT NULL COMMENT '카테고리 ID',
  category_path VARCHAR(255) DEFAULT NULL COMMENT '카테고리 경로 (검색 최적화용 캐싱, 예: /1/2/5/)',
  origin VARCHAR(50) DEFAULT NULL COMMENT '원산지 문자열 저장용',
  manufacturer VARCHAR(100) DEFAULT NULL COMMENT '제조사',
  brand VARCHAR(100) DEFAULT NULL COMMENT '브랜드',
  name VARCHAR(255) NOT NULL COMMENT '상품명',
  invoice_name VARCHAR(255) DEFAULT NULL COMMENT '택배송장 출력용 상품명',
  goods_type VARCHAR(20) NOT NULL DEFAULT 'NORMAL' COMMENT '상품타입(NORMAL/HEALTH/MEDICAL)',
  goods_status VARCHAR(20) NOT NULL DEFAULT 'NEW' COMMENT '상품상태(NEW/USED/REFURB)',
  adult_only VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '성인전용 여부(Y/N)',
  search_keywords VARCHAR(500) DEFAULT NULL COMMENT '상품 검색 키워드',
  search_text TEXT COMMENT '상품명/키워드 검색용 suffix 토큰',
  tax_type VARCHAR(20) NOT NULL DEFAULT 'TAX' COMMENT '과세여부(TAX/FREE)',
  supply_price INT NOT NULL DEFAULT 0 COMMENT '공급가 (공급사 정산용)',
  sell_price INT NOT NULL DEFAULT 0 COMMENT '판매가 (판매사 구매용)',
  sell_price_fixed VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '판매가 고정 여부(Y/N)',
  price_policy VARCHAR(20) NOT NULL DEFAULT 'FREE' COMMENT '가격정책 (FREE: 가격자율, COMPLY: 가격준수)',
  compliance_price INT NOT NULL DEFAULT 0 COMMENT '준수가격 (가격준수 시 노출 및 적용)',
  shipping_type VARCHAR(20) NOT NULL DEFAULT 'FREE' COMMENT '배송비 정책(FREE/PAID/QUANTITY/COD)',
  shipping_fee INT NOT NULL DEFAULT 0 COMMENT '기본 배송비',
  shipping_qty_limit INT NOT NULL DEFAULT 1 COMMENT '합포장 기준 수량',
  has_extra_shipping VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '추가배송비 사용여부(Y/N)',
  extra_shipping_jeju INT NOT NULL DEFAULT 0 COMMENT '제주도 추가 배송비',
  extra_shipping_island INT NOT NULL DEFAULT 0 COMMENT '도서산간 추가 배송비',
  return_shipping_fee INT NOT NULL DEFAULT 0 COMMENT '반품 배송비 (편도)',
  exchange_shipping_fee INT NOT NULL DEFAULT 0 COMMENT '교환 배송비 (왕복)',
  stock INT NOT NULL DEFAULT 0 COMMENT '재고수량',
  stock_link VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '재고 연동 여부(Y/N)',
  soldout TINYINT NOT NULL DEFAULT 0 COMMENT '품절 여부 (0: 판매중, 1: 품절)',
  is_display VARCHAR(20) NOT NULL DEFAULT 'Y' COMMENT '노출 여부 (Y/N)',
  is_exportable VARCHAR(20) NOT NULL DEFAULT 'Y' COMMENT 'API/다운로드 허용 여부 (Y/N)',
  has_option VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '옵션 사용 여부 (Y/N)',
  has_text_option VARCHAR(20) NOT NULL DEFAULT 'N' COMMENT '텍스트 입력 옵션 사용 여부(Y/N)',
  option_title1 VARCHAR(100) DEFAULT NULL COMMENT '옵션 분류명 1 (예: 색상)',
  option_title2 VARCHAR(100) DEFAULT NULL COMMENT '옵션 항목명 1 또는 옵션 분류명 2',
  option_title3 VARCHAR(100) DEFAULT NULL COMMENT '옵션 항목명 2',
  has_soldout_option TINYINT NOT NULL DEFAULT 0 COMMENT '부분 옵션 품절 포함 여부 (0:없음, 1:있음)',
  thumbnail_url VARCHAR(255) DEFAULT NULL COMMENT '대표 이미지 URL',
  content TEXT COMMENT '상품 상세 설명(에디터 내용)',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL COMMENT '소프트삭제 일시',
  UNIQUE KEY uk_vendor_goods_code (vendor_code, vendor_goods_code),
  FULLTEXT KEY ft_goods_search_text (search_text),
  KEY idx_goods_admin_list (deleted_at, is_display, soldout, created_at, id),
  KEY idx_goods_vendor_list (vendor_code, deleted_at, created_at, id),
  KEY idx_goods_category_list (category_path, deleted_at, created_at, id),
  KEY idx_goods_type_status (goods_type, goods_status, deleted_at),
  KEY idx_soldout (soldout),
  KEY idx_is_display (is_display),
  KEY idx_category_id (category_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='상품 정보 테이블';
