CREATE TABLE `members` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '고유 식별자',
  `user_id` varchar(50) NOT NULL COMMENT '로그인 아이디',
  `vendor_code` varchar(20) NOT NULL COMMENT '회원 고유 공급사 코드 (예: V000001ZAC)',
  `password` varchar(255) NOT NULL COMMENT 'Bcrypt 해시 비밀번호',
  `role` varchar(20) NOT NULL COMMENT '회원 구분 (ADMIN, SELLER, VENDOR)',
  `name` varchar(50) NOT NULL COMMENT '이름 또는 대표자명',
  `email` varchar(100) DEFAULT NULL COMMENT '이메일 주소',
  `company_name` varchar(100) DEFAULT NULL COMMENT '상호명(회사명)',
  `business_number` varchar(30) DEFAULT NULL COMMENT '사업자등록번호',
  `business_type` varchar(50) DEFAULT NULL COMMENT '업태',
  `business_item` varchar(50) DEFAULT NULL COMMENT '종목',
  `business_license_file` varchar(255) DEFAULT NULL COMMENT '사업자등록증 사본 이미지 경로',
  `zipcode` varchar(10) DEFAULT NULL COMMENT '우편번호',
  `address` varchar(150) DEFAULT NULL COMMENT '기본 주소',
  `address_detail` varchar(150) DEFAULT NULL COMMENT '상세 주소',
  `bank_name` varchar(50) DEFAULT NULL COMMENT '은행명',
  `account_number` varchar(100) DEFAULT NULL COMMENT '계좌번호',
  `account_holder` varchar(50) DEFAULT NULL COMMENT '예금주',
  `bank_book_file` varchar(255) DEFAULT NULL COMMENT '통장 사본 이미지 경로',
  `is_email_agreed` tinyint(1) DEFAULT '1' COMMENT '이메일 수신 동의 (1:동의, 0:거부)',
  `is_sms_agreed` tinyint(1) DEFAULT '1' COMMENT 'SMS 수신 동의 (1:동의, 0:거부)',
  `approval_status` varchar(20) DEFAULT 'PENDING' COMMENT '사업자 승인 상태',
  `deposit` int DEFAULT '0' COMMENT '적립금 잔액',
  `mileage` int DEFAULT '0' COMMENT '포인트 잔액',
  `level_id` int unsigned DEFAULT NULL COMMENT '회원 등급 식별자',
  `mobile` varchar(20) DEFAULT NULL COMMENT '휴대폰 번호',
  `company_phone` varchar(20) DEFAULT NULL COMMENT '업장 전화번호',
  `fax` varchar(20) DEFAULT NULL COMMENT '팩스 번호',
  `status` varchar(20) DEFAULT 'ACTIVE' COMMENT '계정 상태 (ACTIVE:정상, SUSPENDED:정지, WITHDRAWN:탈퇴)',
  `login_fail_count` tinyint unsigned DEFAULT '0' COMMENT '로그인 연속 실패 횟수',
  `locked_until` datetime DEFAULT NULL COMMENT '계정 잠금 해제 시간',
  `last_login_at` datetime DEFAULT NULL COMMENT '마지막 로그인 시간',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '가입일',
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_id` (`user_id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `uk_vendor_code` (`vendor_code`),
  KEY `idx_role_status_approval_id` (`role`,`status`,`approval_status`,`id`),
  KEY `idx_created_id` (`created_at`,`id`),
  KEY `idx_last_login_id` (`last_login_at`,`id`),
  KEY `idx_deposit_id` (`deposit`,`id`),
  KEY `idx_mileage_id` (`mileage`,`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='통합 회원 테이블';
